# Generated by Django 5.0.6 on 2024-05-23 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social_Media_App", "0002_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_signup",
            name="fullname",
        ),
    ]
