# Generated by Django 5.0.6 on 2024-05-23 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social_Media_App", "0003_remove_user_signup_fullname"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_Profile",
        ),
    ]
