# Generated by Django 5.0.6 on 2024-05-23 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Social_Media_App", "0005_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
